### ISSUE TITLE
"No staking found at this address"

### ISSUE THREAD

**Issue by pat-s** [James-Sangalli/dot-staking-income#10]
Tried both with a DOT and a KSM account.

Could it be that the API endpoints have changed? Other sites (e.g. koinly) are also having trouble with these networks atm.

Thanks for this tool!

**Comment by JamesANZ** [comment]
Hi @pat-s 

Coingecko routinely blocks my server IP but I just manually updated the prices so it should work for you if you try it now. 

On a side note: I have never used Koinly before; has it been able to accurately record your staking income? Why use this tool if Koinly can do it? 

Cool profile btw, you work on some cool stuff!

**Comment by pat-s** [comment]
> Coingecko routinely blocks my server IP but I just manually updated the prices so it should work for you if you try it now.

Ah you use coingecko which has no support for user API keys, I see.

I just started trying out Koinly - apparently they make use of subscan.io which just recently changed their API endpoints and hence the import is currently broken.

![image](https://user-images.githubusercontent.com/8430564/131650760-9d7077c6-2f6c-4b9a-82b3-bb6ae98343fe.png)

Maybe subscan.io could also be an option for you?

Koinly might adjust their API scraping soon but having an external FOSS option might still be preferred.

> Cool profile btw, you work on some cool stuff!

Thanks, always nice to hear 😃

**Comment by JamesANZ** [comment]
> > Coingecko routinely blocks my server IP but I just manually updated the prices so it should work for you if you try it now.
> 
> Ah you use coingecko which has no support for user API keys, I see.
> 
> I just started trying out Koinly - apparently they make use of subscan.io which just recently changed their API endpoints and hence the import is currently broken.
> 
> ![image](https://user-images.githubusercontent.com/8430564/131650760-9d7077c6-2f6c-4b9a-82b3-bb6ae98343fe.png)
> 
> Maybe subscan.io could also be an option for you?
> 
> Koinly might adjust their API scraping soon but having an external FOSS option might still be preferred.
> 
> > Cool profile btw, you work on some cool stuff!
> 
> Thanks, always nice to hear 😃

I use the subscan API to get the staking history, they have an endpoint for prices but it's in USD only and it get's throttled easily as it does not give you historical prices. Coingecko's API is good but for some reason they have throttled my server indefinitely. My workaround is to update the historical prices locally and push them up as you can see here:  https://github.com/James-Sangalli/dot-staking-income/blob/master/package.json#L8

I just updated it again so it should work for you if you try it today.
