### ISSUE TITLE
Automatic price updates

### ISSUE THREAD

**Issue by gabrieljaegerde** [James-Sangalli/dot-staking-income#13]
Based on your commits I am assuming that price updates are manual?

**Comment by JamesANZ** [comment]
Yes, might look into doing it automatically

**Comment by gabrieljaegerde** [comment]
Yeah, I think setting up a job that runs every x hours would do.

**Comment by JamesANZ** [comment]
https://github.com/James-Sangalli/dot-staking-income/commit/b5bdfdb963435604145e36eee04f0ceed5b215b4
